//---------------------------------------------------------------------------
// File name:    lang.h                  Revision Date: 2007.05.10
//---------------------------------------------------------------------------
// This file is used both for compiling the wLaunchELF program,
// with default language definitions, and when loading alternate
// language definitions at runtime. For the latter case it is the
// intention that an edited version of this file be used, where
// each string constant has been replaced by one suitable for the
// language to be used. Only the quoted strings should be edited
// for such use, as changing other parts of the lines could cause
// malfunction. The index number controls where in the program a
// string gets used, and the 'name' part is an identifying symbol
// that should remain untranslated even for translated versions,
// so that we can use them as a common reference independent both
// of the language used, and of the index number. Those names do
// not have any effect on loading alternate language definitions.
//--------------------------------------------------------------
// clang-format off
lang(0, Net_Config, "Config. Rede")
lang(1, Init_Delay, "Atraso Inicial")
lang(2, TIMEOUT, "TEMPO LIMITE")
lang(3, Halted, "Pausado")
lang(4, LEFT, "ESQUERDA")
lang(5, RIGHT, "DIREITA")
lang(6, PUSH_ANY_BUTTON_or_DPAD, "APERTE QUALQUER BOTÃO ou D-PAD")
lang(7, Loading_HDL_Info_Module, "Carregando Módulo HDL Info...")
lang(8, Loading_HDD_Modules, "Carregando Módulos HDD...")
lang(9, Loading_NetFS_and_FTP_Server_Modules, "Carregando Módulos NetFS e Servidor FTP...")
lang(10, Valid, "Válido")
lang(11, Bogus, "Inválido")
lang(12, CNF_Path, "Caminho CNF")
lang(13, is_Not_Found, "não foi encontrado")
//--------------------------------------------------------------
lang(14, MISC, "MISC")
lang(15, PS2Disc, "Disco PS2")
lang(16, FileBrowser, "Navegador de Arquivos")
lang(17, PS2Browser, "Navegador PS2")
lang(18, PS2Net, "Rede PS2")
lang(19, PS2PowerOff, "Desligar PS2")
lang(20, HddManager, "Gerenciador HDD")
lang(21, TextEditor, "Editor de Texto")
lang(22, JpgViewer, "Visualizador Jpg")
lang(23, Configure, "Configurar")
lang(24, Load_CNFprev, "Carregar CNF--")
lang(25, Load_CNFnext, "Carregar CNF++")
lang(26, Set_CNF_Path, "Definir Caminho CNF")
lang(27, Load_CNF, "Carregar CNF")
lang(28, ShowFont, "Mostrar Fonte")
//--------------------------------------------------------------
lang(29, Reading_SYSTEMCNF, "Lendo SYSTEM.CNF...")
lang(30, Failed, "Falhou")
lang(31, Powering_Off_Console, "Desligando Console...")
lang(32, No_Disc, "Sem Disco")
lang(33, Detecting_Disc, "Detectando Disco")
lang(34, Stop_Disc, "Parar Disco")
lang(35, auto, "automático")
lang(36, Circle, "Círculo")
lang(37, Cross, "Cruz")
lang(38, Square, "Quadrado")
lang(39, Triangle, "Triângulo")
lang(40, Failed_To_Save, "Falha ao Salvar")
lang(41, Saved_Failed, "Salvamento Falhou")
lang(42, Saved_Config, "Config. Salva")
lang(43, Saved, "Salvo")
lang(44, Failed_writing, "Falha ao escrever")
lang(45, Failed_To_Load, "Falha ao Carregar")
lang(46, Loaded_Config, "Config. Carregada")
//--------------------------------------------------------------
lang(47, SKIN_SETTINGS, "CONFIGURAÇÕES DA SKIN")
lang(48, Skin_Path, "Caminho da Skin")
lang(49, Apply_New_Skin, "Aplicar Nova Skin")
lang(50, Brightness, "Brilho")
lang(51, Edit, "Editar")
lang(52, Clear, "Limpar")
lang(53, Add, "Adicionar")
lang(54, Subtract, "Subtrair")
lang(55, OK, "OK")
lang(56, CANCEL, "CANCELAR")
lang(57, Cancel, "Cancelar")
lang(58, Browse, "Navegar")
lang(59, Change, "Mudar")
lang(60, Return, "Voltar")
lang(61, PasteRename, "Colar+Renomear")
lang(62, Back, "Voltar")
lang(63, Use, "Usar")
lang(64, Set, "Definir")
lang(65, Page_leftright, "Pág. esquerda/direita")
lang(66, Edit_Title, "Editar Título")
lang(67, Left, "Esquerda")
lang(68, Right, "Direita")
lang(69, Up, "Cima")
lang(70, Enter, "Entrar")
lang(71, Choose, "Escolher")
lang(72, RevMark, "Desmarcar")
lang(73, TitleOFF, "Título DESL")
lang(74, TitleON, "Título LIG")
lang(75, Menu, "Menu")
lang(76, PathPad, "PathPad")
lang(77, Exit, "Sair")
lang(78, View, "Visualizar")
lang(79, Thumb, "Miniatura")
lang(80, List, "Lista")
lang(81, SlideShow, "Apres. Slides")
lang(82, Sel, "Sel.")
lang(83, BackSpace, "Apagar")
lang(84, Mark, "Marcar")
lang(85, CrLf, "Cr/Lf")
lang(86, Cr, "Cr")
lang(87, Lf, "Lf")
lang(88, Ins, "Ins")
lang(89, On, "Ligado")
lang(90, Off, "Desligado")
lang(91, Open_KeyBoard, "Abrir Teclado")
lang(92, Close_KB, "Fechar TC")
lang(93, free, "livre")
lang(94, Color, "Cor")
lang(95, Backgr, "Fundo")
lang(96, Frames, "Molduras")
lang(97, Select, "Seleção")
lang(98, Normal, "Normal")
lang(99, Graph, "Gráfico")
lang(100, TV_mode, "Modo TV")
lang(101, Screen_X_offset, "Deslocamento X da Tela")
lang(102, Screen_Y_offset, "Deslocamento Y da Tela")
lang(103, Interlace, "Entrelaçamento")
lang(104, ON, "LIG")
lang(105, OFF, "DESL")
lang(106, Skin_Settings, "Config. da Skin")
lang(107, Menu_Title, "Título do Menu")
lang(108, NULL, "NULO")
lang(109, NONE, "NENHUM")
lang(110, DEFAULT, "PADRÃO")
lang(111, Menu_Frame, "Moldura do Menu")
lang(112, Popups_Opaque, "Popups Opacos")
lang(113, Use_Default_Screen_Settings, "Usar Config. de Tela Padrão")
//--------------------------------------------------------------
lang(114, STARTUP_SETTINGS, "CONFIGURAÇÕES DE INICIALIZAÇÃO")
lang(115, Reset_IOP, "Resetar IOP")
lang(116, Number_of_CNFs, "Número de CNF's")
lang(117, Pad_mapping, "Mapeamento do Controle")
lang(118, USBD_IRX, "IRX USBD")
lang(119, Initial_Delay, "Atraso Inicial")
lang(120, Default_Timeout, "Tempo Limite 'Padrão'")
lang(121, USB_Keyboard_Used, "Teclado USB em Uso")
lang(122, USB_Keyboard_IRX, "IRX Teclado USB")
lang(123, USB_Keyboard_Map, "Mapa Teclado USB")
lang(124, CNF_Path_override, "Substituir Caminho CNF")
lang(125, USB_Mass_IRX, "IRX USB Mass")
lang(126, Language_File, "Arquivo de Idioma")
//--------------------------------------------------------------
lang(127, NETWORK_SETTINGS, "CONFIGURAÇÕES DE REDE")
lang(128, IP_Address, "Endereço IP")
lang(129, Netmask, "Máscara de Rede")
lang(130, Gateway, "Gateway")
lang(131, Save_to, "Salvar em")
//--------------------------------------------------------------
lang(132, Right_DPad_to_Edit, "D-Pad Direita para Editar")
lang(133, Button_Settings, "Configurações de Botão")
lang(134, Show_launch_titles, "Mostrar títulos de lançamento")
lang(135, Disc_control, "Controle de Disco")
lang(136, Hide_full_ELF_paths, "Ocultar caminhos ELF completos")
lang(137, Screen_Settings, "Configurações de Tela")
lang(138, Startup_Settings, "Configurações de Inicialização")
lang(139, Network_Settings, "Configurações de Rede")
lang(140, Copy, "Copiar")
lang(141, Cut, "Recortar")
lang(142, Paste, "Colar")
lang(143, Delete, "Deletar")
lang(144, New_Dir, "Novo Dir")
lang(145, Get_Size, "Obter Tamanho")
lang(146, mcPaste, "mcColar")
lang(147, psuPaste, "psuColar")
lang(148, Name_conflict_for_this_folder, "Conflito de nome para esta pasta")
lang(149, With_gamesave_title, "Com título do gamesave")
lang(150, Undefined_Not_a_gamesave, "Indefinido (Não é um gamesave)")
lang(151, Do_you_wish_to_overwrite_it, "Deseja sobrescrevê-lo")
lang(152, Pasting_file, "Colando arquivo")
lang(153, Remain_Size, "Tamanho Restante")
lang(154, bytes, "bytes")
lang(155, Kbytes, "Kbytes")
lang(156, Current_Speed, "Velocidade Atual")
lang(157, Unknown, "Desconhecida")
lang(158, Remain_Time, "Tempo Restante")
lang(159, Written_Total, "Total Escrito")
lang(160, Average_Speed, "Velocidade Média")
lang(161, Continue_transfer, "Continuar transferência ?")
lang(162, This_file_isnt_an_ELF, "Este arquivo não é um ELF")
lang(163, Copied_to_the_Clipboard, "Copiado para a Área de Transferência")
lang(164, Mark_Files_Delete, "Deletar Arquivos Marcados ?")
lang(165, deleting, "deletando")
lang(166, Delete_Failed, "Falha ao Deletar")
lang(167, Rename_Failed, "Falha ao Renomear")
lang(168, directory_already_exists, "diretório já existe")
lang(169, NewDir_Failed, "Falha ao Criar Novo Dir")
lang(170, Created_folder, "Pasta criada")
lang(171, Path, "Caminho")
lang(172, Checking_Size, "Verificando Tamanho...")
lang(173, size_result, "resultado do tamanho")
lang(174, Size_test_Failed, "Falha no Teste de Tamanho")
lang(175, mctype, "mctype")
lang(176, Pasting, "Colando...")
lang(177, Paste_Failed, "Falha ao Colar")
lang(178, pasting, "colando")
lang(179, Reading_HDD_Information, "Lendo Informações do HDD...")
lang(180, Found, "Encontrado")
lang(181, MB, "MB")
lang(182, GB, "GB")
lang(183, HDD_Information_Read, "Informações do HDD Lidas")
lang(184, Create, "Criar")
lang(185, Remove, "Remover")
lang(186, Rename, "Renomear")
lang(187, Expand, "Expandir")
lang(188, Format, "Formatar")
lang(189, Creating_New_Partition, "Criando Nova Partição...")
lang(190, New_Partition_Created, "Nova Partição Criada")
lang(191, Failed_Creating_New_Partition, "Falha ao Criar Nova Partição")
lang(192, Removing_Current_Partition, "Removendo Partição Atual...")
lang(193, Partition_Removed, "Partição Removida")
lang(194, Failed_Removing_Current_Partition, "Falha ao Remover Partição Atual")
lang(195, Renaming_Partition, "Renomeando Partição...")
lang(196, Partition_Renamed, "Partição Renomeada")
lang(197, Failed_Renaming_Partition, "Falha ao Renomear Partição")
lang(198, Renaming_Game, "Renomeando Jogo...")
lang(199, Game_Renamed, "Jogo Renomeado")
lang(200, Failed_Renaming_Game, "Falha ao Renomear Jogo")
lang(201, Expanding_Current_Partition, "Expandindo Partição Atual...")
lang(202, Partition_Expanded, "Partição Expandida")
lang(203, Failed_Expanding_Current_Partition, "Falha ao Expandir Partição Atual")
lang(204, Formating_HDD, "Formatando HDD...")
lang(205, HDD_Formated, "HDD Formatado")
lang(206, HDD_Format_Failed, "Falha ao Formatar HDD")
lang(207, Create_New_Partition, "Criar Nova Partição ?")
lang(208, Remove_Current_Partition, "Remover Partição Atual ?")
lang(209, Enter_New_Partition_Name, "Digite o Novo Nome da Partição.")
lang(210, Rename_Current_Game, "Renomear Jogo Atual ?")
lang(211, Rename_Current_Partition, "Renomear Partição Atual ?")
lang(212, Select_New_Partition_Size_In_MB, "Selecione o Novo Tamanho da Partição em MB.")
lang(213, Expand_Current_Partition, "Expandir Partição Atual ?")
lang(214, Format_HDD, "Formatar o HDD inteiro (destrói todas as partições) ?")
lang(215, HDD_STATUS, "STATUS DO HDD")
lang(216, CONNECTED, "CONECTADO")
lang(217, FORMATED, "FORMATADO")
lang(218, YES, "SIM")
lang(219, NO, "NÃO")
lang(220, HDD_SIZE, "TAMANHO DO HDD")
lang(221, HDD_USED, "HDD EM USO")
lang(222, HDD_FREE, "HDD LIVRE")
lang(223, FREE, "LIVRE")
lang(224, Raw_SIZE, "TAMANHO Bruto")
lang(225, Reserved_for_system, "Reservado para o sistema")
lang(226, Inaccessible, "Inacessível")
lang(227, HDL_SIZE, "TAMANHO HDL")
lang(228, Info_not_loaded, "Info não carregada")
lang(229, GAME_INFORMATION, "INFORMAÇÕES DO JOGO")
lang(230, STARTUP, "INICIALIZAÇÃO")
lang(231, SIZE, "TAMANHO")
lang(232, TYPE_DVD_GAME, "TIPO: JOGO DVD")
lang(233, TYPE_CD_GAME, "TIPO: JOGO CD")
lang(234, PFS_SIZE, "TAMANHO PFS")
lang(235, PFS_USED, "PFS EM USO")
lang(236, PFS_FREE, "PFS LIVRE")
lang(237, MENU, "MENU")
lang(238, Load_HDL_Game_Info, "Carregar HDL Game Info")
lang(239, PS2_HDD_MANAGER, "GERENCIADOR DE HDD DO PS2")
lang(240, New, "Novo")
lang(241, Open, "Abrir")
lang(242, Close, "Fechar")
lang(243, Save, "Salvar")
lang(244, Save_As, "Salvar Como")
lang(245, Windows, "Janelas")
lang(246, Free_Window, "Janela Livre")
lang(247, Window_Not_Yet_Saved, "Janela Não Salva")
lang(248, File_Created, "Arquivo Criado")
lang(249, Failed_Creating_File, "Falha ao Criar Arquivo")
lang(250, File_Opened, "Arquivo Aberto")
lang(251, Failed_Opening_File, "Falha ao Abrir Arquivo")
lang(252, File_Not_Yet_Saved, "Arquivo Não Salvo")
lang(253, File_Not_Yet_Saved_Closed, "Arquivo Não Salvo Fechado")
lang(254, File_Closed, "Arquivo %s Fechado")
lang(255, File_Saved, "Arquivo Salvo")
lang(256, Failed_Saving_File, "Falha ao Salvar Arquivo")
lang(257, Enter_File_Name, "Digite o Nome do Arquivo.")
lang(258, Exiting_Editor, "Saindo do Editor...")
lang(259, Exit_Without_Saving, "Sair Sem Salvar ?")
lang(260, Select_A_File_For_Editing, "Selecione um Arquivo Para Edição")
lang(261, Close_Without_Saving, "Fechar Sem Salvar ?")
lang(262, MARK, "MARCAR")
lang(263, COPY, "COPIAR")
lang(264, CUT, "RECORTAR")
lang(265, PASTE, "COLAR")
lang(266, LINE_UP, "LINHA ACIMA")
lang(267, LINE_DOWN, "LINHA ABAIXO")
lang(268, PAGE_UP, "PÁG. ACIMA")
lang(269, PAGE_DOWN, "PÁG. ABAIXO")
lang(270, HOME, "INÍCIO")
lang(271, END, "FIM")
lang(272, INSERT, "INSERIR")
lang(273, RET_CRLF, "RET CR/LF")
lang(274, RET_CR, "RET CR")
lang(275, RET_LF, "RET LF")
lang(276, TAB, "TAB")
lang(277, SPACE, "ESPAÇO")
lang(278, RETURN, "RETORNO")
lang(279, PS2_TEXT_EDITOR, "EDITOR DE TEXTO DO PS2")
lang(280, Start_StartStop_Slideshow, "Start: Iniciar/Parar Apres. Slides")
lang(281, L1R1_Slideshow_Timer, "L1/R1: Temporizador Apres. Slides")
lang(282, L2R2_Slideshow_Transition, "L2/R2: Transição Apres. Slides")
lang(283, LeftRight_Pad_PrevNext_Picture, "D-Pad Esquerda/Direita: Imagem Ant/Próx")
lang(284, UpDown_Pad_Rotate_Picture, "D-Pad Cima/Baixo: Rotacionar Imagem")
lang(285, Left_Joystick_Panorama, "Joystick Esquerdo: Panorama")
lang(286, Right_Joystick_Vertical_Zoom, "Joystick Direito Vertical: Zoom")
lang(287, FullScreen_Mode, "Modo Tela Cheia")
lang(288, Exit_To_Jpg_Browser, "Sair Para o Navegador Jpg")
lang(289, Jpg_Viewer, "Visualizador Jpg")
lang(290, Picture, "Imagem")
lang(291, Size, "Tamanho")
lang(292, Command_List, "Lista de Comandos")
lang(293, Timer, "Temporizador")
lang(294, Transition, "Transição")
lang(295, Zoom, "Zoom")
lang(296, Fade, "Desvanecer")
lang(297, ZoomFade, "Zoom+Desvanecer")
//--------------------------------------------------------------
// Startup Setting Font file Added
lang(298, Font_File, "Arquivo de Fonte")
//--------------------------------------------------------------
// New MISC entry for debug info
// Note that substrings in that info screen should NEVER have
// any language definitions made for them, as they can and will
// differ between versions, depending on current debug needs.
// So only the name of the MISC entry itself should be defined.
lang(299, Debug_Info, "Info Debug")
//--------------------------------------------------------------
// New FileBrowser display modes and sort modes added
lang(300, Mode, "Modo")
lang(301, Show_Content_as, "Mostrar Conteúdo como")
lang(302, Filename, "Nome do Arquivo")
lang(303, Game_Title, "Título do Jogo")
lang(304, _plus_Details, " + Detalhes")
lang(305, Sort_Content_by, "Ordenar Conteúdo por")
lang(306, No_Sort, "Sem Ordem")
lang(307, Timestamp, "Data/Hora")
lang(308, Back_to_Browser, "Voltar ao Navegador")
//--------------------------------------------------------------
// New Icon setup command added
lang(309, New_Icon, "Novo Ícone")
lang(310, file_alredy_exists, "arquivo já existe")
lang(311, Icon_Title, "Título do Ícone")
lang(312, IconText, "Texto do Ícone")
//--------------------------------------------------------------
lang(313, KB_RETURN, "RETORNO")
//--------------------------------------------------------------
// New GUI Skin option added
lang(314, GUI, "GUI")
lang(315, Apply_GUI_Skin, "Aplicar Skin da GUI")
lang(316, Skin_Preview, "Pré-visualização da Skin")
lang(317, Halt, "Pausar")  // Alternative Halted text, added for main screen skinning purposes, only appears when main screen skin is active
lang(318, Delay, "Atraso")            // Same reason as above
lang(319, Show_Menu, "Mostrar Menu")
//---------------------------------------------------------------------------
// New skin file commands added
lang(320, Load_Skin_CNF, "Carregar CNF da Skin")
lang(321, Save_Skin_CNF, "Salvar CNF da Skin")
//---------------------------------------------------------------------------
// New FileBrowser command for virtual memory cards
lang(322, Mount, "Montar")
//---------------------------------------------------------------------------
// New MISC entry for "About uLE" screen display
lang(323, About_uLE, "Sobre o uLE")
//---------------------------------------------------------------------------
// New MISC entry for "OSDSYS(MC)" launch (for FMCB on incompatible consoles)
lang(324, OSDSYS, "OSDSYS")
// for hdl_game_unload
lang(325, Unload_HDL_Game_Info, "Descarregar HDL Game Info")
//---------------------------------------------------------------------------
// New status message for HDD information read, when there are too many partitions.
lang(326, HDD_Information_Read_Overflow, "Informações do HDD Lidas (truncado)")

    // clang-format on
    //---------------------------------------------------------------------------
    // End of file:  lang.h
    //---------------------------------------------------------------------------